import type {
  Booking,
  Car,
  CarFeatureSet,
  Review,
  Transaction,
  User,
} from './types'
import { addDays, todayISO } from './format'

/** Seed data so every screen renders before the API is wired up. */

const img = (id: string, w = 1200) =>
  `https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=${w}&q=70`

const features = (on: (keyof CarFeatureSet)[]): CarFeatureSet => ({
  airConditioning: false,
  bluetooth: false,
  gps: false,
  reverseCamera: false,
  cruiseControl: false,
  usbPorts: false,
  leatherSeats: false,
  sunroof: false,
  childSeat: false,
  androidAuto: false,
  ...Object.fromEntries(on.map((k) => [k, true])),
})

export const owners: User[] = [
  {
    id: 'u-owner-1',
    name: 'Chidi Okonkwo',
    email: 'chidi@autogo.ng',
    phone: '+234 803 111 2233',
    role: 'owner',
    verification: 'verified',
    status: 'active',
    createdAt: '2023-03-14',
  },
  {
    id: 'u-owner-2',
    name: 'Amara Bello',
    email: 'amara@autogo.ng',
    phone: '+234 806 444 5566',
    role: 'owner',
    verification: 'verified',
    status: 'active',
    createdAt: '2022-11-02',
  },
  {
    id: 'u-owner-3',
    name: 'Tunde Adeyemi',
    email: 'tunde@autogo.ng',
    phone: '+234 810 777 8899',
    role: 'owner',
    verification: 'pending',
    status: 'active',
    createdAt: '2024-06-21',
  },
]

const basePolicy = {
  mileageLimitPerDay: 250,
  fuelPolicy: 'full-to-full' as const,
  minRentalDays: 1,
  cancellationWindowHours: 48,
  securityDeposit: 100_000,
  driverAgeMin: 23,
}

const insurance = (provider: string, months: number) => ({
  provider,
  policyNumber: `POL-${Math.abs(hash(provider))}`.slice(0, 14),
  coverage: 'Comprehensive — third party, fire, theft and collision damage waiver',
  expiresAt: addDays(todayISO(), months * 30),
})

function hash(s: string) {
  let h = 0
  for (let i = 0; i < s.length; i++) h = (h << 5) - h + s.charCodeAt(i)
  return h
}

/** Blocks out a couple of near-term windows so the availability check has teeth. */
function blocked(offsets: [number, number][]) {
  const out: string[] = []
  for (const [from, to] of offsets) {
    for (let i = from; i <= to; i++) out.push(addDays(todayISO(), i))
  }
  return out
}

export const cars: Car[] = [
  {
    id: 'car-1',
    ownerId: 'u-owner-1',
    name: 'Toyota Camry SE',
    brand: 'Toyota',
    model: 'Camry',
    year: 2022,
    bodyType: 'sedan',
    transmission: 'automatic',
    fuelType: 'petrol',
    seats: 5,
    color: 'Pearl White',
    registrationNumber: 'LAG-472-KJA',
    vin: '4T1BF1FK5CU512345',
    mileage: 38_400,
    pricePerDay: 45_000,
    pricePerWeek: 270_000,
    pricePerMonth: 990_000,
    pickupLocation: 'Lekki Phase 1, Lagos',
    city: 'Lagos',
    description:
      'Clean, well-serviced Camry with full leather interior. Ideal for airport runs, corporate hire and weekend trips. Serviced every 5,000km at the Toyota dealership.',
    features: features([
      'airConditioning',
      'bluetooth',
      'gps',
      'reverseCamera',
      'cruiseControl',
      'usbPorts',
      'leatherSeats',
      'androidAuto',
    ]),
    specs: { engine: '2.5L 4-cylinder', horsepower: 203, driveType: 'fwd', doors: 4 },
    policy: basePolicy,
    insurance: insurance('AIICO Insurance', 9),
    images: [
      img('1550355291-bbee04a92027'),
      img('1503376780353-7e6692767b70'),
      img('1494976388531-d1058494cdd8'),
      img('1533473359331-0135ef1b58bf'),
    ],
    gpsTrackerId: 'TRK-88213',
    status: 'approved',
    rating: 4.8,
    reviewCount: 34,
    tripCount: 61,
    unavailableDates: blocked([
      [3, 6],
      [18, 20],
    ]),
    createdAt: '2024-08-11',
  },
  {
    id: 'car-2',
    ownerId: 'u-owner-2',
    name: 'Toyota Land Cruiser Prado',
    brand: 'Toyota',
    model: 'Prado',
    year: 2021,
    bodyType: 'suv',
    transmission: 'automatic',
    fuelType: 'diesel',
    seats: 7,
    color: 'Metallic Grey',
    registrationNumber: 'ABJ-901-XLB',
    vin: 'JTEBU29J1550012B7',
    mileage: 64_200,
    pricePerDay: 95_000,
    pricePerWeek: 580_000,
    pricePerMonth: 2_150_000,
    pickupLocation: 'Wuse 2, Abuja',
    city: 'Abuja',
    description:
      'Powerful 7-seat Prado built for long-distance travel and rough roads. Popular for executive transport, weddings and inter-state trips. Driver available on request.',
    features: features([
      'airConditioning',
      'bluetooth',
      'gps',
      'reverseCamera',
      'cruiseControl',
      'usbPorts',
      'leatherSeats',
      'sunroof',
      'childSeat',
    ]),
    specs: { engine: '2.8L turbo diesel', horsepower: 201, driveType: '4wd', doors: 5 },
    policy: { ...basePolicy, securityDeposit: 250_000, minRentalDays: 2 },
    insurance: insurance('Leadway Assurance', 14),
    images: [
      img('1519641471654-76ce0107ad1b'),
      img('1533106418989-88406c7cc8ca'),
      img('1552519507-da3b142c6e3d'),
    ],
    gpsTrackerId: 'TRK-88410',
    status: 'approved',
    rating: 4.9,
    reviewCount: 52,
    tripCount: 88,
    unavailableDates: blocked([[8, 14]]),
    createdAt: '2024-05-30',
  },
  {
    id: 'car-3',
    ownerId: 'u-owner-1',
    name: 'Honda Accord Sport',
    brand: 'Honda',
    model: 'Accord',
    year: 2020,
    bodyType: 'sedan',
    transmission: 'automatic',
    fuelType: 'petrol',
    seats: 5,
    color: 'Modern Steel',
    registrationNumber: 'LAG-118-MUS',
    mileage: 71_800,
    pricePerDay: 38_000,
    pricePerWeek: 228_000,
    pricePerMonth: 840_000,
    pickupLocation: 'Ikeja GRA, Lagos',
    city: 'Lagos',
    description:
      'Sporty, fuel-efficient Accord with a smooth ride. A dependable everyday rental for city driving and business meetings.',
    features: features([
      'airConditioning',
      'bluetooth',
      'reverseCamera',
      'cruiseControl',
      'usbPorts',
      'androidAuto',
    ]),
    specs: { engine: '1.5L turbo', horsepower: 192, driveType: 'fwd', doors: 4 },
    policy: basePolicy,
    insurance: insurance('AXA Mansard', 6),
    images: [img('1606664515524-ed2f786a0bd6'), img('1502877338535-766e1452684a')],
    status: 'approved',
    rating: 4.6,
    reviewCount: 21,
    tripCount: 40,
    unavailableDates: [],
    createdAt: '2024-09-02',
  },
  {
    id: 'car-4',
    ownerId: 'u-owner-2',
    name: 'Mercedes-Benz GLE 450',
    brand: 'Mercedes-Benz',
    model: 'GLE 450',
    year: 2023,
    bodyType: 'suv',
    transmission: 'automatic',
    fuelType: 'hybrid',
    seats: 5,
    color: 'Obsidian Black',
    registrationNumber: 'LAG-770-VIC',
    vin: 'WDC0G8EB6LF701234',
    mileage: 18_900,
    pricePerDay: 165_000,
    pricePerWeek: 1_020_000,
    pricePerMonth: 3_800_000,
    pickupLocation: 'Victoria Island, Lagos',
    city: 'Lagos',
    description:
      'Flagship luxury SUV with mild-hybrid drivetrain, Burmester sound and massaging front seats. Chauffeur service available at extra cost.',
    features: features([
      'airConditioning',
      'bluetooth',
      'gps',
      'reverseCamera',
      'cruiseControl',
      'usbPorts',
      'leatherSeats',
      'sunroof',
      'androidAuto',
    ]),
    specs: { engine: '3.0L inline-6 EQ Boost', horsepower: 362, driveType: 'awd', doors: 5 },
    policy: { ...basePolicy, securityDeposit: 500_000, driverAgeMin: 28, mileageLimitPerDay: 200 },
    insurance: insurance('Custodian Insurance', 20),
    images: [
      img('1618843479313-40f8afb4b4d8'),
      img('1563720223185-11003d516935'),
      img('1617814076367-b759c7d7e738'),
    ],
    gpsTrackerId: 'TRK-90055',
    status: 'approved',
    rating: 5,
    reviewCount: 12,
    tripCount: 15,
    unavailableDates: blocked([[1, 4]]),
    createdAt: '2025-01-19',
  },
  {
    id: 'car-5',
    ownerId: 'u-owner-3',
    name: 'Kia Rio Hatchback',
    brand: 'Kia',
    model: 'Rio',
    year: 2019,
    bodyType: 'hatchback',
    transmission: 'manual',
    fuelType: 'petrol',
    seats: 5,
    color: 'Signal Red',
    registrationNumber: 'PHC-330-EKY',
    mileage: 92_300,
    pricePerDay: 22_000,
    pricePerWeek: 132_000,
    pricePerMonth: 480_000,
    pickupLocation: 'GRA Phase 2, Port Harcourt',
    city: 'Port Harcourt',
    description:
      'Compact, economical and easy to park. The cheapest way to get around town for a few days.',
    features: features(['airConditioning', 'bluetooth', 'usbPorts']),
    specs: { engine: '1.4L 4-cylinder', horsepower: 120, driveType: 'fwd', doors: 5 },
    policy: { ...basePolicy, securityDeposit: 50_000, mileageLimitPerDay: 180 },
    insurance: insurance('NEM Insurance', 4),
    images: [img('1552519507-da3b142c6e3d'), img('1541899481282-d53bffe3c35d')],
    status: 'pending',
    rating: 4.3,
    reviewCount: 8,
    tripCount: 13,
    unavailableDates: [],
    createdAt: '2025-02-04',
  },
  {
    id: 'car-6',
    ownerId: 'u-owner-1',
    name: 'Tesla Model 3 Long Range',
    brand: 'Tesla',
    model: 'Model 3',
    year: 2023,
    bodyType: 'sedan',
    transmission: 'automatic',
    fuelType: 'electric',
    seats: 5,
    color: 'Deep Blue Metallic',
    registrationNumber: 'LAG-005-EVX',
    vin: '5YJ3E1EA7PF123456',
    mileage: 12_500,
    pricePerDay: 120_000,
    pricePerWeek: 740_000,
    pricePerMonth: 2_700_000,
    pickupLocation: 'Ikoyi, Lagos',
    city: 'Lagos',
    description:
      'Fully electric with roughly 500km of range. Home charger included with rentals of 3 days or more. Autopilot enabled.',
    features: features([
      'airConditioning',
      'bluetooth',
      'gps',
      'reverseCamera',
      'cruiseControl',
      'usbPorts',
      'leatherSeats',
      'sunroof',
    ]),
    specs: { engine: 'Dual motor electric', horsepower: 346, driveType: 'awd', doors: 4 },
    policy: { ...basePolicy, fuelPolicy: 'same-to-same', securityDeposit: 300_000 },
    insurance: insurance('Leadway Assurance', 11),
    images: [
      img('1560958089-b8a1929cea89'),
      img('1536700503339-1e4b06520771'),
      img('1571127236794-81c0bbfe1ce3'),
    ],
    gpsTrackerId: 'TRK-91777',
    status: 'approved',
    rating: 4.9,
    reviewCount: 27,
    tripCount: 33,
    unavailableDates: blocked([[10, 12]]),
    createdAt: '2024-12-08',
  },
  {
    id: 'car-7',
    ownerId: 'u-owner-3',
    name: 'Ford Ranger Wildtrak',
    brand: 'Ford',
    model: 'Ranger',
    year: 2021,
    bodyType: 'pickup',
    transmission: 'automatic',
    fuelType: 'diesel',
    seats: 5,
    color: 'Sabre Orange',
    registrationNumber: 'KAN-611-TRK',
    mileage: 58_100,
    pricePerDay: 72_000,
    pricePerWeek: 430_000,
    pricePerMonth: 1_580_000,
    pickupLocation: 'Nassarawa, Kano',
    city: 'Kano',
    description:
      'Double-cab pickup that handles construction sites, farm runs and rough terrain without complaint. Tow bar fitted.',
    features: features([
      'airConditioning',
      'bluetooth',
      'gps',
      'reverseCamera',
      'usbPorts',
      'cruiseControl',
    ]),
    specs: { engine: '2.0L bi-turbo diesel', horsepower: 210, driveType: '4wd', doors: 4 },
    policy: { ...basePolicy, mileageLimitPerDay: 400, securityDeposit: 150_000 },
    insurance: insurance('Sovereign Trust', 8),
    images: [img('1519641471654-76ce0107ad1b'), img('1533473359331-0135ef1b58bf')],
    status: 'approved',
    rating: 4.5,
    reviewCount: 16,
    tripCount: 29,
    unavailableDates: [],
    createdAt: '2024-10-27',
  },
  {
    id: 'car-8',
    ownerId: 'u-owner-2',
    name: 'Hyundai Elantra',
    brand: 'Hyundai',
    model: 'Elantra',
    year: 2022,
    bodyType: 'sedan',
    transmission: 'automatic',
    fuelType: 'petrol',
    seats: 5,
    color: 'Fluid Metal',
    registrationNumber: 'IBD-284-QWE',
    mileage: 44_600,
    pricePerDay: 33_000,
    pricePerWeek: 198_000,
    pricePerMonth: 720_000,
    pickupLocation: 'Bodija, Ibadan',
    city: 'Ibadan',
    description:
      'Sharp-looking sedan with excellent fuel economy and a big boot. Great value for longer bookings.',
    features: features([
      'airConditioning',
      'bluetooth',
      'reverseCamera',
      'usbPorts',
      'androidAuto',
      'cruiseControl',
    ]),
    specs: { engine: '2.0L 4-cylinder', horsepower: 147, driveType: 'fwd', doors: 4 },
    policy: basePolicy,
    insurance: insurance('AIICO Insurance', 5),
    images: [img('1502877338535-766e1452684a'), img('1494976388531-d1058494cdd8')],
    status: 'approved',
    rating: 4.4,
    reviewCount: 19,
    tripCount: 31,
    unavailableDates: blocked([[22, 26]]),
    createdAt: '2024-07-15',
  },
  {
    id: 'car-9',
    ownerId: 'u-owner-1',
    name: 'Lexus RX 350',
    brand: 'Lexus',
    model: 'RX 350',
    year: 2020,
    bodyType: 'suv',
    transmission: 'automatic',
    fuelType: 'petrol',
    seats: 5,
    color: 'Nebula Grey',
    registrationNumber: 'LAG-946-RXL',
    mileage: 69_400,
    pricePerDay: 85_000,
    pricePerWeek: 510_000,
    pricePerMonth: 1_880_000,
    pickupLocation: 'Surulere, Lagos',
    city: 'Lagos',
    description:
      'The default choice for comfortable Lagos driving — quiet cabin, high seating position and bulletproof reliability.',
    features: features([
      'airConditioning',
      'bluetooth',
      'gps',
      'reverseCamera',
      'cruiseControl',
      'usbPorts',
      'leatherSeats',
      'sunroof',
      'childSeat',
    ]),
    specs: { engine: '3.5L V6', horsepower: 295, driveType: 'awd', doors: 5 },
    policy: { ...basePolicy, securityDeposit: 200_000 },
    insurance: insurance('AXA Mansard', 12),
    images: [
      img('1617814076367-b759c7d7e738'),
      img('1563720223185-11003d516935'),
      img('1550355291-bbee04a92027'),
    ],
    gpsTrackerId: 'TRK-89120',
    status: 'approved',
    rating: 4.7,
    reviewCount: 41,
    tripCount: 74,
    unavailableDates: blocked([[5, 7]]),
    createdAt: '2024-04-03',
  },
  {
    id: 'car-10',
    ownerId: 'u-owner-3',
    name: 'Toyota Sienna',
    brand: 'Toyota',
    model: 'Sienna',
    year: 2019,
    bodyType: 'van',
    transmission: 'automatic',
    fuelType: 'petrol',
    seats: 8,
    color: 'Celestial Silver',
    registrationNumber: 'ENU-517-VAN',
    mileage: 104_700,
    pricePerDay: 55_000,
    pricePerWeek: 330_000,
    pricePerMonth: 1_200_000,
    pickupLocation: 'Independence Layout, Enugu',
    city: 'Enugu',
    description:
      'Eight-seat people carrier for family trips, church outings and airport transfers. Plenty of luggage space behind the third row.',
    features: features([
      'airConditioning',
      'bluetooth',
      'reverseCamera',
      'usbPorts',
      'childSeat',
    ]),
    specs: { engine: '3.5L V6', horsepower: 296, driveType: 'fwd', doors: 5 },
    policy: { ...basePolicy, minRentalDays: 2 },
    insurance: insurance('NEM Insurance', 7),
    images: [img('1541899481282-d53bffe3c35d'), img('1503376780353-7e6692767b70')],
    status: 'approved',
    rating: 4.2,
    reviewCount: 11,
    tripCount: 22,
    unavailableDates: [],
    createdAt: '2024-11-11',
  },
  {
    id: 'car-11',
    ownerId: 'u-owner-2',
    name: 'BMW 3 Series 330i',
    brand: 'BMW',
    model: '330i',
    year: 2022,
    bodyType: 'sedan',
    transmission: 'automatic',
    fuelType: 'petrol',
    seats: 5,
    color: 'Alpine White',
    registrationNumber: 'LAG-330-BMW',
    mileage: 26_800,
    pricePerDay: 98_000,
    pricePerWeek: 590_000,
    pricePerMonth: 2_180_000,
    pickupLocation: 'Oniru, Lagos',
    city: 'Lagos',
    description:
      'Rear-wheel-drive sports sedan with adaptive suspension. The one to book when the drive itself is the point.',
    features: features([
      'airConditioning',
      'bluetooth',
      'gps',
      'reverseCamera',
      'cruiseControl',
      'usbPorts',
      'leatherSeats',
      'sunroof',
      'androidAuto',
    ]),
    specs: { engine: '2.0L turbo', horsepower: 255, driveType: 'rwd', doors: 4 },
    policy: { ...basePolicy, driverAgeMin: 25, securityDeposit: 300_000 },
    insurance: insurance('Custodian Insurance', 16),
    images: [
      img('1555215695-3004980ad54e'),
      img('1580273916550-e323be2ae537'),
      img('1606664515524-ed2f786a0bd6'),
    ],
    gpsTrackerId: 'TRK-92330',
    status: 'approved',
    rating: 4.8,
    reviewCount: 23,
    tripCount: 36,
    unavailableDates: blocked([[15, 17]]),
    createdAt: '2024-09-25',
  },
  {
    id: 'car-12',
    ownerId: 'u-owner-3',
    name: 'Volkswagen Golf GTI',
    brand: 'Volkswagen',
    model: 'Golf GTI',
    year: 2021,
    bodyType: 'hatchback',
    transmission: 'manual',
    fuelType: 'petrol',
    seats: 5,
    color: 'Tornado Red',
    registrationNumber: 'ABJ-207-GTI',
    mileage: 41_200,
    pricePerDay: 62_000,
    pricePerWeek: 372_000,
    pricePerMonth: 1_360_000,
    pickupLocation: 'Maitama, Abuja',
    city: 'Abuja',
    description:
      'Hot hatch with a six-speed manual and plaid seats. Compact enough for the city, quick enough for the open road.',
    features: features([
      'airConditioning',
      'bluetooth',
      'gps',
      'reverseCamera',
      'usbPorts',
      'androidAuto',
      'cruiseControl',
    ]),
    specs: { engine: '2.0L TSI turbo', horsepower: 241, driveType: 'fwd', doors: 5 },
    policy: { ...basePolicy, driverAgeMin: 25 },
    insurance: insurance('Sovereign Trust', 10),
    images: [img('1580273916550-e323be2ae537'), img('1555215695-3004980ad54e')],
    status: 'rejected',
    rating: 4.6,
    reviewCount: 9,
    tripCount: 14,
    unavailableDates: [],
    createdAt: '2025-01-30',
  },
].map((car) => ({
  ...car,
  owner: (() => {
    const o = owners.find((x) => x.id === car.ownerId)!
    return {
      id: o.id,
      name: o.name,
      avatarUrl: o.avatarUrl,
      verification: o.verification,
      createdAt: o.createdAt,
    }
  })(),
})) as Car[]

export const customers: User[] = [
  {
    id: 'u-cust-1',
    name: 'Ngozi Eze',
    email: 'ngozi@example.com',
    phone: '+234 802 300 4411',
    role: 'customer',
    verification: 'verified',
    status: 'active',
    createdAt: '2024-02-18',
  },
  {
    id: 'u-cust-2',
    name: 'Samuel Ojo',
    email: 'samuel@example.com',
    phone: '+234 815 220 9080',
    role: 'customer',
    verification: 'pending',
    status: 'active',
    createdAt: '2025-01-06',
  },
  {
    id: 'u-cust-3',
    name: 'Fatima Sani',
    email: 'fatima@example.com',
    phone: '+234 909 118 2244',
    role: 'customer',
    verification: 'verified',
    status: 'suspended',
    createdAt: '2023-09-29',
  },
]

export const admins: User[] = [
  {
    id: 'u-admin-1',
    name: 'AUTOGO Admin',
    email: 'admin@autogo.ng',
    role: 'admin',
    verification: 'verified',
    status: 'active',
    createdAt: '2022-01-01',
  },
]

export const allUsers: User[] = [...admins, ...owners, ...customers]

const bookingRenter = (u: User) => ({
  fullName: u.name,
  email: u.email,
  phone: u.phone ?? '',
  licenseNumber: `DL-${Math.abs(hash(u.id))}`.slice(0, 12),
  licenseExpiry: '2028-05-30',
  emergencyContactName: 'Next of kin',
  emergencyContactPhone: '+234 800 000 0000',
})

export const bookings: Booking[] = [
  {
    id: 'bk-1',
    reference: 'AG-8F2K91',
    carId: 'car-1',
    customerId: 'u-cust-1',
    ownerId: 'u-owner-1',
    startDate: addDays(todayISO(), 3),
    endDate: addDays(todayISO(), 6),
    days: 4,
    pickupLocation: 'Lekki Phase 1, Lagos',
    renter: bookingRenter(customers[0]),
    subtotal: 180_000,
    serviceFee: 18_000,
    insuranceFee: 14_000,
    total: 212_000,
    status: 'confirmed',
    paymentStatus: 'paid',
    paymentReference: 'PSK_29fj20d',
    createdAt: addDays(todayISO(), -2),
  },
  {
    id: 'bk-2',
    reference: 'AG-3JQ77C',
    carId: 'car-2',
    customerId: 'u-cust-2',
    ownerId: 'u-owner-2',
    startDate: addDays(todayISO(), 8),
    endDate: addDays(todayISO(), 14),
    days: 7,
    pickupLocation: 'Wuse 2, Abuja',
    renter: bookingRenter(customers[1]),
    subtotal: 580_000,
    serviceFee: 58_000,
    insuranceFee: 24_500,
    total: 662_500,
    status: 'pending',
    paymentStatus: 'unpaid',
    createdAt: addDays(todayISO(), -1),
  },
  {
    id: 'bk-3',
    reference: 'AG-1PD40M',
    carId: 'car-9',
    customerId: 'u-cust-1',
    ownerId: 'u-owner-1',
    startDate: addDays(todayISO(), -20),
    endDate: addDays(todayISO(), -16),
    days: 5,
    pickupLocation: 'Surulere, Lagos',
    renter: bookingRenter(customers[0]),
    subtotal: 425_000,
    serviceFee: 42_500,
    insuranceFee: 17_500,
    total: 485_000,
    status: 'completed',
    paymentStatus: 'paid',
    paymentReference: 'PSK_10ab77x',
    createdAt: addDays(todayISO(), -27),
  },
  {
    id: 'bk-4',
    reference: 'AG-6RT23V',
    carId: 'car-6',
    customerId: 'u-cust-3',
    ownerId: 'u-owner-1',
    startDate: addDays(todayISO(), -8),
    endDate: addDays(todayISO(), -5),
    days: 4,
    pickupLocation: 'Ikoyi, Lagos',
    renter: bookingRenter(customers[2]),
    subtotal: 480_000,
    serviceFee: 48_000,
    insuranceFee: 14_000,
    total: 542_000,
    status: 'cancelled',
    paymentStatus: 'refunded',
    paymentReference: 'PSK_55zq01p',
    createdAt: addDays(todayISO(), -15),
  },
  {
    id: 'bk-5',
    reference: 'AG-9LM55B',
    carId: 'car-4',
    customerId: 'u-cust-2',
    ownerId: 'u-owner-2',
    startDate: addDays(todayISO(), 1),
    endDate: addDays(todayISO(), 4),
    days: 4,
    pickupLocation: 'Victoria Island, Lagos',
    renter: bookingRenter(customers[1]),
    subtotal: 660_000,
    serviceFee: 66_000,
    insuranceFee: 14_000,
    total: 740_000,
    status: 'active',
    paymentStatus: 'paid',
    paymentReference: 'PSK_78hh22k',
    createdAt: addDays(todayISO(), -6),
  },
].map((b) => {
  const car = cars.find((c) => c.id === b.carId)!
  return {
    ...b,
    car: {
      id: car.id,
      name: car.name,
      brand: car.brand,
      model: car.model,
      images: car.images,
      pickupLocation: car.pickupLocation,
    },
  }
}) as Booking[]

export const reviews: Review[] = [
  {
    id: 'rv-1',
    carId: 'car-1',
    bookingId: 'bk-3',
    author: { id: 'u-cust-1', name: 'Ngozi Eze' },
    rating: 5,
    comment:
      'Spotless car and Chidi was waiting at the pickup point ten minutes early. Handover took five minutes. Would book again without hesitation.',
    photos: [],
    ownerReply: {
      comment: 'Thank you Ngozi! Always a pleasure — see you on the next trip.',
      createdAt: addDays(todayISO(), -14),
    },
    createdAt: addDays(todayISO(), -15),
  },
  {
    id: 'rv-2',
    carId: 'car-1',
    bookingId: 'bk-3',
    author: { id: 'u-cust-2', name: 'Samuel Ojo' },
    rating: 4,
    comment:
      'Great car, drove beautifully on the Lagos–Ibadan expressway. Only note is that the fuel was slightly under full at pickup.',
    photos: [],
    createdAt: addDays(todayISO(), -32),
  },
  {
    id: 'rv-3',
    carId: 'car-2',
    bookingId: 'bk-2',
    author: { id: 'u-cust-3', name: 'Fatima Sani' },
    rating: 5,
    comment:
      'Took the Prado to Jos and back with five people and luggage. Comfortable the whole way, air conditioning ice cold.',
    photos: [],
    createdAt: addDays(todayISO(), -9),
  },
  {
    id: 'rv-4',
    carId: 'car-4',
    bookingId: 'bk-5',
    author: { id: 'u-cust-1', name: 'Ngozi Eze' },
    rating: 5,
    comment: 'Genuinely a special car. Amara is professional and the paperwork was seamless.',
    photos: [],
    createdAt: addDays(todayISO(), -4),
  },
]

export const transactions: Transaction[] = [
  {
    id: 'tx-1',
    bookingId: 'bk-1',
    reference: 'PSK_29fj20d',
    type: 'payment',
    amount: 212_000,
    channel: 'card',
    status: 'success',
    createdAt: addDays(todayISO(), -2),
  },
  {
    id: 'tx-2',
    bookingId: 'bk-3',
    reference: 'PSK_10ab77x',
    type: 'payment',
    amount: 485_000,
    channel: 'bank-transfer',
    status: 'success',
    createdAt: addDays(todayISO(), -27),
  },
  {
    id: 'tx-3',
    bookingId: 'bk-3',
    reference: 'PYT_10ab77x',
    type: 'payout',
    amount: 425_000,
    channel: 'bank-transfer',
    status: 'success',
    createdAt: addDays(todayISO(), -14),
  },
  {
    id: 'tx-4',
    bookingId: 'bk-4',
    reference: 'PSK_55zq01p',
    type: 'refund',
    amount: 542_000,
    channel: 'card',
    status: 'success',
    createdAt: addDays(todayISO(), -12),
  },
  {
    id: 'tx-5',
    bookingId: 'bk-5',
    reference: 'PSK_78hh22k',
    type: 'payment',
    amount: 740_000,
    channel: 'wallet',
    status: 'success',
    createdAt: addDays(todayISO(), -6),
  },
]

export const testimonials = [
  {
    id: 't-1',
    name: 'Ngozi Eze',
    role: 'Renter, Lagos',
    rating: 5,
    quote:
      'I booked a Camry for a four-day work trip and had the keys in my hand within an hour. The price I saw was the price I paid.',
  },
  {
    id: 't-2',
    name: 'Chidi Okonkwo',
    role: 'Car owner, Lagos',
    rating: 5,
    quote:
      'My two cars used to sit idle between contracts. On AUTOGO they earn about ₦600,000 a month and payouts land the day after each trip.',
  },
  {
    id: 't-3',
    name: 'Fatima Sani',
    role: 'Renter, Abuja',
    rating: 5,
    quote:
      'The GPS tracking gave my family real peace of mind on a long inter-state drive. Support answered on the first ring.',
  },
]
