import type {
  Booking,
  Car,
  CarFeatureSet,
  Review,
  Transaction,
  User,
} from './types'
import { addDays, todayISO } from './format'

/** Seed data so every screen renders before the API is wired up. */

const img = (id: string, w = 1200) =>
  `https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=${w}&q=70`

const features = (on: (keyof CarFeatureSet)[]): CarFeatureSet => ({
  airConditioning: false,
  bluetooth: false,
  gps: false,
  reverseCamera: false,
  cruiseControl: false,
  usbPorts: false,
  leatherSeats: false,
  sunroof: false,
  childSeat: false,
  androidAuto: false,
  ...Object.fromEntries(on.map((k) => [k, true])),
})

export const owners: User[] = [
  {
    id: 'u-owner-1',
    name: 'Chidi Okonkwo',
    email: 'chidi@autogo.ng',
    phone: '+234 803 111 2233',
    role: 'owner',
    verification: 'verified',
    status: 'active',
    createdAt: '2023-03-14',
  },
  {
    id: 'u-owner-2',
    name: 'Amara Bello',
    email: 'amara@autogo.ng',
    phone: '+234 806 444 5566',
    role: 'owner',
    verification: 'verified',
    status: 'active',
    createdAt: '2022-11-02',
  },
  {
    id: 'u-owner-3',
    name: 'Tunde Adeyemi',
    email: 'tunde@autogo.ng',
    phone: '+234 810 777 8899',
    role: 'owner',
    verification: 'pending',
    status: 'active',
    createdAt: '2024-06-21',
  },
]

const basePolicy = {
  mileageLimitPerDay: 250,
  fuelPolicy: 'full-to-full' as const,
  minRentalDays: 1,
  cancellationWindowHours: 48,
  securityDeposit: 100_000,
  driverAgeMin: 23,
}

const insurance = (provider: string, months: number) => ({
  provider,
  policyNumber: `POL-${Math.abs(hash(provider))}`.slice(0, 14),
  coverage: 'Comprehensive â€” third party, fire, theft and collision damage waiver',
  expiresAt: addDays(todayISO(), months * 30),
})

function hash(s: string) {
  let h = 0
  for (let i = 0; i < s.length; i++) h = (h << 5) - h + s.charCodeAt(i)
  return h
}

/** Blocks out a couple of near-term windows so the availability check has teeth. */
function blocked(offsets: [number, number][]) {
  const out: string[] = []
  for (const [from, to] of offsets) {
    for (let i = from; i <= to; i++) out.push(addDays(todayISO(), i))
  }
  return out
}

export const cars: Car[] = [
  {
    // photo: red Hyundai i30 N Line hatchback
    id: 'car-1',
    ownerId: 'u-owner-1',
    name: 'Hyundai i30 N Line',
    brand: 'Hyundai',
    model: 'i30 N Line',
    year: 2021,
    bodyType: 'hatchback',
    transmission: 'automatic',
    fuelType: 'petrol',
    seats: 5,
    color: 'Passion Red',
    registrationNumber: 'LAG-118-HYN',
    mileage: 41_200,
    pricePerDay: 32_000,
    pricePerWeek: 192_000,
    pricePerMonth: 700_000,
    pickupLocation: 'Ikeja GRA, Lagos',
    city: 'Lagos',
    description:
      'Sharp-looking hatchback that is quick, easy to park and genuinely fun on a clear road. Ideal for city driving and short trips.',
    features: features([
      'airConditioning',
      'bluetooth',
      'reverseCamera',
      'usbPorts',
      'androidAuto',
      'cruiseControl',
    ]),
    specs: { engine: '1.6L turbo', horsepower: 201, driveType: 'fwd', doors: 5 },
    policy: basePolicy,
    insurance: insurance('AIICO Insurance', 9),
    images: [img('1550355291-bbee04a92027')],
    status: 'approved',
    rating: 4.6,
    reviewCount: 2,
    tripCount: 44,
    unavailableDates: blocked([
      [3, 6],
      [18, 20],
    ]),
    createdAt: '2024-08-11',
  },
  {
    // photo: white Honda CR-V
    id: 'car-2',
    ownerId: 'u-owner-2',
    name: 'Honda CR-V',
    brand: 'Honda',
    model: 'CR-V',
    year: 2020,
    bodyType: 'suv',
    transmission: 'automatic',
    fuelType: 'petrol',
    seats: 5,
    color: 'Platinum White',
    registrationNumber: 'ABJ-901-HND',
    mileage: 58_600,
    pricePerDay: 58_000,
    pricePerWeek: 348_000,
    pricePerMonth: 1_280_000,
    pickupLocation: 'Wuse 2, Abuja',
    city: 'Abuja',
    description:
      'Comfortable, economical family SUV with a big boot and a high driving position. A dependable choice for long inter-state journeys.',
    features: features([
      'airConditioning',
      'bluetooth',
      'gps',
      'reverseCamera',
      'cruiseControl',
      'usbPorts',
      'childSeat',
    ]),
    specs: { engine: '1.5L turbo', horsepower: 190, driveType: 'awd', doors: 5 },
    policy: { ...basePolicy, securityDeposit: 150_000 },
    insurance: insurance('Leadway Assurance', 14),
    images: [img('1519641471654-76ce0107ad1b')],
    status: 'approved',
    rating: 4.7,
    reviewCount: 1,
    tripCount: 71,
    unavailableDates: blocked([[8, 14]]),
    createdAt: '2024-05-30',
  },
  {
    // photo: white Ford Expedition
    id: 'car-3',
    ownerId: 'u-owner-3',
    name: 'Ford Expedition',
    brand: 'Ford',
    model: 'Expedition',
    year: 2019,
    bodyType: 'suv',
    transmission: 'automatic',
    fuelType: 'petrol',
    seats: 7,
    color: 'Oxford White',
    registrationNumber: 'KAN-611-FRD',
    mileage: 78_400,
    pricePerDay: 88_000,
    pricePerWeek: 528_000,
    pricePerMonth: 1_950_000,
    pickupLocation: 'Nassarawa, Kano',
    city: 'Kano',
    description:
      'Full-size seven-seat SUV with serious luggage room. Popular for family travel, weddings and group airport transfers.',
    features: features([
      'airConditioning',
      'bluetooth',
      'gps',
      'reverseCamera',
      'cruiseControl',
      'usbPorts',
      'leatherSeats',
      'childSeat',
    ]),
    specs: { engine: '3.5L V6 EcoBoost', horsepower: 375, driveType: '4wd', doors: 5 },
    policy: { ...basePolicy, minRentalDays: 2, securityDeposit: 200_000 },
    insurance: insurance('Sovereign Trust', 8),
    images: [img('1533473359331-0135ef1b58bf')],
    gpsTrackerId: 'TRK-88410',
    status: 'approved',
    rating: 4.5,
    reviewCount: 0,
    tripCount: 29,
    unavailableDates: [],
    createdAt: '2024-10-27',
  },
  {
    // photo: black Range Rover Sport
    id: 'car-4',
    ownerId: 'u-owner-2',
    name: 'Range Rover Sport',
    brand: 'Land Rover',
    model: 'Range Rover Sport',
    year: 2021,
    bodyType: 'suv',
    transmission: 'automatic',
    fuelType: 'diesel',
    seats: 5,
    color: 'Santorini Black',
    registrationNumber: 'LAG-770-RRS',
    vin: 'SALWR2RE4LA700123',
    mileage: 32_800,
    pricePerDay: 175_000,
    pricePerWeek: 1_050_000,
    pricePerMonth: 3_900_000,
    pickupLocation: 'Victoria Island, Lagos',
    city: 'Lagos',
    description:
      'Executive SUV with air suspension and a beautifully quiet cabin. The default choice for corporate hire and airport pickups.',
    features: features([
      'airConditioning',
      'bluetooth',
      'gps',
      'reverseCamera',
      'cruiseControl',
      'usbPorts',
      'leatherSeats',
      'sunroof',
      'androidAuto',
    ]),
    specs: { engine: '3.0L turbo diesel', horsepower: 296, driveType: '4wd', doors: 5 },
    policy: {
      ...basePolicy,
      securityDeposit: 500_000,
      driverAgeMin: 28,
      mileageLimitPerDay: 200,
    },
    insurance: insurance('Custodian Insurance', 20),
    images: [img('1563720223185-11003d516935')],
    gpsTrackerId: 'TRK-90055',
    status: 'approved',
    rating: 4.9,
    reviewCount: 1,
    tripCount: 38,
    unavailableDates: blocked([[1, 4]]),
    createdAt: '2025-01-19',
  },
  {
    // photo: white Tesla Model 3
    id: 'car-5',
    ownerId: 'u-owner-1',
    name: 'Tesla Model 3 Long Range',
    brand: 'Tesla',
    model: 'Model 3',
    year: 2023,
    bodyType: 'sedan',
    transmission: 'automatic',
    fuelType: 'electric',
    seats: 5,
    color: 'Pearl White',
    registrationNumber: 'LAG-005-EVX',
    vin: '5YJ3E1EA7PF123456',
    mileage: 12_500,
    pricePerDay: 120_000,
    pricePerWeek: 740_000,
    pricePerMonth: 2_700_000,
    pickupLocation: 'Ikoyi, Lagos',
    city: 'Lagos',
    description:
      'Fully electric with roughly 500km of range. Home charger included on rentals of three days or more. Autopilot enabled.',
    features: features([
      'airConditioning',
      'bluetooth',
      'gps',
      'reverseCamera',
      'cruiseControl',
      'usbPorts',
      'leatherSeats',
      'sunroof',
    ]),
    specs: { engine: 'Dual motor electric', horsepower: 346, driveType: 'awd', doors: 4 },
    policy: { ...basePolicy, fuelPolicy: 'same-to-same', securityDeposit: 300_000 },
    insurance: insurance('Leadway Assurance', 11),
    images: [img('1560958089-b8a1929cea89')],
    gpsTrackerId: 'TRK-91777',
    status: 'approved',
    rating: 4.9,
    reviewCount: 0,
    tripCount: 33,
    unavailableDates: blocked([[10, 12]]),
    createdAt: '2024-12-08',
  },
  {
    // photo: silver Tesla Model 3
    id: 'car-6',
    ownerId: 'u-owner-3',
    name: 'Tesla Model 3',
    brand: 'Tesla',
    model: 'Model 3',
    year: 2022,
    bodyType: 'sedan',
    transmission: 'automatic',
    fuelType: 'electric',
    seats: 5,
    color: 'Quicksilver',
    registrationNumber: 'ABJ-207-EVT',
    mileage: 24_100,
    pricePerDay: 105_000,
    pricePerWeek: 630_000,
    pricePerMonth: 2_320_000,
    pickupLocation: 'Maitama, Abuja',
    city: 'Abuja',
    description:
      'Quiet, quick and cheap to run. Charges overnight on a standard socket and covers Abuja for a week on one charge.',
    features: features([
      'airConditioning',
      'bluetooth',
      'gps',
      'reverseCamera',
      'cruiseControl',
      'usbPorts',
    ]),
    specs: { engine: 'Rear motor electric', horsepower: 283, driveType: 'rwd', doors: 4 },
    policy: { ...basePolicy, fuelPolicy: 'same-to-same', securityDeposit: 250_000 },
    insurance: insurance('AXA Mansard', 12),
    images: [img('1571127236794-81c0bbfe1ce3')],
    status: 'approved',
    rating: 4.8,
    reviewCount: 0,
    tripCount: 21,
    unavailableDates: [],
    createdAt: '2024-11-11',
  },
  {
    // photo: black Tesla Model S
    id: 'car-7',
    ownerId: 'u-owner-2',
    name: 'Tesla Model S',
    brand: 'Tesla',
    model: 'Model S',
    year: 2021,
    bodyType: 'sedan',
    transmission: 'automatic',
    fuelType: 'electric',
    seats: 5,
    color: 'Solid Black',
    registrationNumber: 'LAG-946-TMS',
    mileage: 38_900,
    pricePerDay: 155_000,
    pricePerWeek: 930_000,
    pricePerMonth: 3_450_000,
    pickupLocation: 'Lekki Phase 1, Lagos',
    city: 'Lagos',
    description:
      'Flagship electric saloon â€” silent, extremely quick, and comfortable over long distances. Ideal for executive transport.',
    features: features([
      'airConditioning',
      'bluetooth',
      'gps',
      'reverseCamera',
      'cruiseControl',
      'usbPorts',
      'leatherSeats',
      'sunroof',
    ]),
    specs: { engine: 'Dual motor electric', horsepower: 670, driveType: 'awd', doors: 4 },
    policy: {
      ...basePolicy,
      fuelPolicy: 'same-to-same',
      securityDeposit: 400_000,
      driverAgeMin: 25,
    },
    insurance: insurance('Custodian Insurance', 16),
    images: [img('1536700503339-1e4b06520771')],
    gpsTrackerId: 'TRK-92330',
    status: 'approved',
    rating: 5,
    reviewCount: 0,
    tripCount: 17,
    unavailableDates: blocked([[15, 17]]),
    createdAt: '2024-09-25',
  },
  {
    // photo: blue Volkswagen Polo
    id: 'car-8',
    ownerId: 'u-owner-3',
    name: 'Volkswagen Polo',
    brand: 'Volkswagen',
    model: 'Polo',
    year: 2019,
    bodyType: 'hatchback',
    transmission: 'manual',
    fuelType: 'petrol',
    seats: 5,
    color: 'Reef Blue',
    registrationNumber: 'PHC-330-VWP',
    mileage: 86_300,
    pricePerDay: 24_000,
    pricePerWeek: 144_000,
    pricePerMonth: 520_000,
    pickupLocation: 'GRA Phase 2, Port Harcourt',
    city: 'Port Harcourt',
    description:
      'Compact, economical and easy to park. The cheapest way to get around town for a few days.',
    features: features(['airConditioning', 'bluetooth', 'usbPorts']),
    specs: { engine: '1.4L 4-cylinder', horsepower: 128, driveType: 'fwd', doors: 5 },
    policy: { ...basePolicy, securityDeposit: 50_000, mileageLimitPerDay: 180 },
    insurance: insurance('NEM Insurance', 4),
    images: [img('1541899481282-d53bffe3c35d')],
    // Left pending on purpose so the admin approval queue isn't empty.
    status: 'pending',
    rating: 0,
    reviewCount: 0,
    tripCount: 0,
    unavailableDates: [],
    createdAt: '2025-02-04',
  },
  {
    // photo: light blue BMW M5
    id: 'car-9',
    ownerId: 'u-owner-2',
    name: 'BMW M5 Competition',
    brand: 'BMW',
    model: 'M5',
    year: 2022,
    bodyType: 'sedan',
    transmission: 'automatic',
    fuelType: 'petrol',
    seats: 5,
    color: 'Brooklyn Grey',
    registrationNumber: 'LAG-330-BMW',
    mileage: 26_800,
    pricePerDay: 165_000,
    pricePerWeek: 990_000,
    pricePerMonth: 3_650_000,
    pickupLocation: 'Oniru, Lagos',
    city: 'Lagos',
    description:
      'A saloon that behaves like a supercar. Book it when the drive itself is the point â€” and mind the speed limits.',
    features: features([
      'airConditioning',
      'bluetooth',
      'gps',
      'reverseCamera',
      'cruiseControl',
      'usbPorts',
      'leatherSeats',
      'sunroof',
      'androidAuto',
    ]),
    specs: { engine: '4.4L twin-turbo V8', horsepower: 617, driveType: 'awd', doors: 4 },
    policy: {
      ...basePolicy,
      driverAgeMin: 30,
      securityDeposit: 600_000,
      mileageLimitPerDay: 150,
    },
    insurance: insurance('Custodian Insurance', 15),
    images: [img('1555215695-3004980ad54e')],
    gpsTrackerId: 'TRK-95001',
    status: 'approved',
    rating: 4.8,
    reviewCount: 0,
    tripCount: 12,
    unavailableDates: blocked([[22, 26]]),
    createdAt: '2024-07-15',
  },
  {
    // photo: grey BMW M4 coupÃ©
    id: 'car-10',
    ownerId: 'u-owner-1',
    name: 'BMW M4 CoupÃ©',
    brand: 'BMW',
    model: 'M4',
    year: 2020,
    bodyType: 'coupe',
    transmission: 'automatic',
    fuelType: 'petrol',
    seats: 4,
    color: 'Nardo Grey',
    registrationNumber: 'LAG-472-BM4',
    mileage: 34_500,
    pricePerDay: 142_000,
    pricePerWeek: 852_000,
    pricePerMonth: 3_150_000,
    pickupLocation: 'Victoria Island, Lagos',
    city: 'Lagos',
    description:
      'Two-door coupÃ© with rear-wheel drive and a proper straight-six. A weekend car, hired by the day.',
    features: features([
      'airConditioning',
      'bluetooth',
      'gps',
      'reverseCamera',
      'cruiseControl',
      'usbPorts',
      'leatherSeats',
      'androidAuto',
    ]),
    specs: { engine: '3.0L twin-turbo inline-6', horsepower: 503, driveType: 'rwd', doors: 2 },
    policy: {
      ...basePolicy,
      driverAgeMin: 28,
      securityDeposit: 450_000,
      mileageLimitPerDay: 150,
    },
    insurance: insurance('AXA Mansard', 10),
    images: [img('1580273916550-e323be2ae537')],
    status: 'approved',
    rating: 4.7,
    reviewCount: 0,
    tripCount: 15,
    unavailableDates: blocked([[5, 7]]),
    createdAt: '2024-04-03',
  },
  {
    // photo: blue BMW 4 Series coupÃ©
    id: 'car-11',
    ownerId: 'u-owner-3',
    name: 'BMW 4 Series',
    brand: 'BMW',
    model: '430i',
    year: 2019,
    bodyType: 'coupe',
    transmission: 'automatic',
    fuelType: 'petrol',
    seats: 4,
    color: 'Estoril Blue',
    registrationNumber: 'IBD-284-BM4',
    mileage: 52_700,
    pricePerDay: 78_000,
    pricePerWeek: 468_000,
    pricePerMonth: 1_720_000,
    pickupLocation: 'Bodija, Ibadan',
    city: 'Ibadan',
    description:
      'Sharp-handling coupÃ© that is still comfortable enough for a long drive. A good step up from the everyday saloon.',
    features: features([
      'airConditioning',
      'bluetooth',
      'reverseCamera',
      'usbPorts',
      'cruiseControl',
      'leatherSeats',
    ]),
    specs: { engine: '2.0L turbo', horsepower: 248, driveType: 'rwd', doors: 2 },
    policy: { ...basePolicy, driverAgeMin: 25, securityDeposit: 250_000 },
    insurance: insurance('AIICO Insurance', 5),
    images: [img('1502877338535-766e1452684a')],
    status: 'approved',
    rating: 4.4,
    reviewCount: 0,
    tripCount: 26,
    unavailableDates: [],
    createdAt: '2024-09-02',
  },
  {
    // photo: black Audi RS6 Avant
    id: 'car-12',
    ownerId: 'u-owner-3',
    name: 'Audi RS6 Avant',
    brand: 'Audi',
    model: 'RS6 Avant',
    year: 2021,
    bodyType: 'sedan',
    transmission: 'automatic',
    fuelType: 'petrol',
    seats: 5,
    color: 'Mythos Black',
    registrationNumber: 'ENU-517-RS6',
    mileage: 29_900,
    pricePerDay: 158_000,
    pricePerWeek: 948_000,
    pricePerMonth: 3_500_000,
    pickupLocation: 'Independence Layout, Enugu',
    city: 'Enugu',
    description:
      'An estate with supercar pace and room for the whole family plus luggage. Genuinely the most useful fast car made.',
    features: features([
      'airConditioning',
      'bluetooth',
      'gps',
      'reverseCamera',
      'cruiseControl',
      'usbPorts',
      'leatherSeats',
      'sunroof',
      'androidAuto',
    ]),
    specs: { engine: '4.0L twin-turbo V8', horsepower: 591, driveType: 'awd', doors: 5 },
    policy: {
      ...basePolicy,
      driverAgeMin: 30,
      securityDeposit: 550_000,
      mileageLimitPerDay: 180,
    },
    insurance: insurance('Leadway Assurance', 7),
    images: [img('1606664515524-ed2f786a0bd6')],
    status: 'approved',
    rating: 4.6,
    reviewCount: 0,
    tripCount: 9,
    unavailableDates: [],
    createdAt: '2024-11-20',
  },
  {
    // photo: grey Mercedes-AMG GT R
    id: 'car-13',
    ownerId: 'u-owner-2',
    name: 'Mercedes-AMG GT R',
    brand: 'Mercedes-Benz',
    model: 'AMG GT R',
    year: 2020,
    bodyType: 'coupe',
    transmission: 'automatic',
    fuelType: 'petrol',
    seats: 2,
    color: 'Designo Selenite Grey',
    registrationNumber: 'LAG-901-AMG',
    vin: 'WDDYJ7JA8LA027781',
    mileage: 14_300,
    pricePerDay: 285_000,
    pricePerWeek: 1_710_000,
    pricePerMonth: 6_300_000,
    pickupLocation: 'Banana Island, Lagos',
    city: 'Lagos',
    description:
      'A two-seat track car with number plates. Hired for photoshoots, weddings and birthdays. Chauffeur available.',
    features: features([
      'airConditioning',
      'bluetooth',
      'gps',
      'reverseCamera',
      'cruiseControl',
      'usbPorts',
      'leatherSeats',
    ]),
    specs: { engine: '4.0L twin-turbo V8', horsepower: 577, driveType: 'rwd', doors: 2 },
    policy: {
      ...basePolicy,
      driverAgeMin: 30,
      securityDeposit: 1_000_000,
      mileageLimitPerDay: 100,
    },
    insurance: insurance('Custodian Insurance', 18),
    images: [img('1618843479313-40f8afb4b4d8')],
    gpsTrackerId: 'TRK-77882',
    status: 'approved',
    rating: 5,
    reviewCount: 0,
    tripCount: 6,
    unavailableDates: blocked([[2, 5]]),
    createdAt: '2025-01-08',
  },
  {
    // photo: blue Chevrolet Camaro SS
    id: 'car-14',
    ownerId: 'u-owner-1',
    name: 'Chevrolet Camaro SS',
    brand: 'Chevrolet',
    model: 'Camaro SS',
    year: 2019,
    bodyType: 'coupe',
    transmission: 'automatic',
    fuelType: 'petrol',
    seats: 4,
    color: 'Riverside Blue',
    registrationNumber: 'LAG-556-CAM',
    mileage: 47_600,
    pricePerDay: 132_000,
    pricePerWeek: 792_000,
    pricePerMonth: 2_920_000,
    pickupLocation: 'Lekki Phase 1, Lagos',
    city: 'Lagos',
    description:
      'American muscle with a V8 soundtrack. Turns heads everywhere and is surprisingly easy to drive in traffic.',
    features: features([
      'airConditioning',
      'bluetooth',
      'reverseCamera',
      'usbPorts',
      'cruiseControl',
      'leatherSeats',
    ]),
    specs: { engine: '6.2L V8', horsepower: 455, driveType: 'rwd', doors: 2 },
    policy: {
      ...basePolicy,
      driverAgeMin: 28,
      securityDeposit: 400_000,
      mileageLimitPerDay: 150,
    },
    insurance: insurance('Sovereign Trust', 6),
    images: [img('1552519507-da3b142c6e3d')],
    status: 'approved',
    rating: 4.7,
    reviewCount: 0,
    tripCount: 19,
    unavailableDates: [],
    createdAt: '2024-06-14',
  },
  {
    // photo: grey Ford Mustang Shelby
    id: 'car-15',
    ownerId: 'u-owner-1',
    name: 'Ford Mustang Shelby GT',
    brand: 'Ford',
    model: 'Mustang Shelby GT',
    year: 2020,
    bodyType: 'coupe',
    transmission: 'manual',
    fuelType: 'petrol',
    seats: 4,
    color: 'Magnetic Grey',
    registrationNumber: 'ABJ-778-MST',
    mileage: 31_500,
    pricePerDay: 148_000,
    pricePerWeek: 888_000,
    pricePerMonth: 3_280_000,
    pickupLocation: 'Wuse 2, Abuja',
    city: 'Abuja',
    description:
      'Six-speed manual Mustang with the Shelby package. For drivers who want to change their own gears.',
    features: features([
      'airConditioning',
      'bluetooth',
      'reverseCamera',
      'usbPorts',
      'leatherSeats',
    ]),
    specs: { engine: '5.0L V8', horsepower: 480, driveType: 'rwd', doors: 2 },
    policy: {
      ...basePolicy,
      driverAgeMin: 30,
      securityDeposit: 450_000,
      mileageLimitPerDay: 150,
    },
    insurance: insurance('NEM Insurance', 9),
    images: [img('1494976388531-d1058494cdd8')],
    status: 'approved',
    rating: 4.8,
    reviewCount: 0,
    tripCount: 11,
    unavailableDates: [],
    createdAt: '2024-10-02',
  },
  {
    // photo: black Porsche Panamera
    id: 'car-16',
    ownerId: 'u-owner-2',
    name: 'Porsche Panamera',
    brand: 'Porsche',
    model: 'Panamera',
    year: 2021,
    bodyType: 'sedan',
    transmission: 'automatic',
    fuelType: 'petrol',
    seats: 4,
    color: 'Jet Black',
    registrationNumber: 'LAG-224-PAN',
    vin: 'WP0AA2A70ML100442',
    mileage: 22_400,
    pricePerDay: 235_000,
    pricePerWeek: 1_410_000,
    pricePerMonth: 5_200_000,
    pickupLocation: 'Ikoyi, Lagos',
    city: 'Lagos',
    description:
      'Four-door Porsche that is as comfortable being driven in as driving. The pick for executive travel and weddings.',
    features: features([
      'airConditioning',
      'bluetooth',
      'gps',
      'reverseCamera',
      'cruiseControl',
      'usbPorts',
      'leatherSeats',
      'sunroof',
      'androidAuto',
    ]),
    specs: { engine: '3.0L turbo V6', horsepower: 325, driveType: 'awd', doors: 4 },
    policy: {
      ...basePolicy,
      driverAgeMin: 30,
      securityDeposit: 800_000,
      mileageLimitPerDay: 150,
    },
    insurance: insurance('Leadway Assurance', 13),
    images: [img('1503376780353-7e6692767b70')],
    gpsTrackerId: 'TRK-22441',
    status: 'approved',
    rating: 4.9,
    reviewCount: 0,
    tripCount: 14,
    unavailableDates: blocked([[9, 11]]),
    createdAt: '2024-12-20',
  },
].map((car) => ({
  ...car,
  owner: (() => {
    const o = owners.find((x) => x.id === car.ownerId)!
    return {
      id: o.id,
      name: o.name,
      avatarUrl: o.avatarUrl,
      verification: o.verification,
      createdAt: o.createdAt,
      phone: o.phone,
    }
  })(),
})) as Car[]

export const customers: User[] = [
  {
    id: 'u-cust-1',
    name: 'Ngozi Eze',
    email: 'ngozi@example.com',
    phone: '+234 802 300 4411',
    role: 'customer',
    verification: 'verified',
    status: 'active',
    createdAt: '2024-02-18',
  },
  {
    id: 'u-cust-2',
    name: 'Samuel Ojo',
    email: 'samuel@example.com',
    phone: '+234 815 220 9080',
    role: 'customer',
    verification: 'pending',
    status: 'active',
    createdAt: '2025-01-06',
  },
  {
    id: 'u-cust-3',
    name: 'Fatima Sani',
    email: 'fatima@example.com',
    phone: '+234 909 118 2244',
    role: 'customer',
    verification: 'verified',
    status: 'suspended',
    createdAt: '2023-09-29',
  },
]

export const admins: User[] = [
  {
    id: 'u-admin-1',
    name: 'AUTOGO Admin',
    email: 'admin@autogo.ng',
    role: 'admin',
    verification: 'verified',
    status: 'active',
    createdAt: '2022-01-01',
  },
]

export const allUsers: User[] = [...admins, ...owners, ...customers]

const bookingRenter = (u: User) => ({
  fullName: u.name,
  email: u.email,
  phone: u.phone ?? '',
  licenseNumber: `DL-${Math.abs(hash(u.id))}`.slice(0, 12),
  licenseExpiry: '2028-05-30',
  emergencyContactName: 'Next of kin',
  emergencyContactPhone: '+234 800 000 0000',
})

export const bookings: Booking[] = [
  {
    id: 'bk-1',
    reference: 'AG-8F2K91',
    carId: 'car-1',
    customerId: 'u-cust-1',
    ownerId: 'u-owner-1',
    startDate: addDays(todayISO(), 3),
    endDate: addDays(todayISO(), 6),
    days: 4,
    pickupLocation: 'Lekki Phase 1, Lagos',
    renter: bookingRenter(customers[0]),
    subtotal: 180_000,
    serviceFee: 18_000,
    insuranceFee: 14_000,
    total: 212_000,
    status: 'confirmed',
    paymentStatus: 'paid',
    paymentReference: 'PSK_29fj20d',
    createdAt: addDays(todayISO(), -2),
  },
  {
    id: 'bk-2',
    reference: 'AG-3JQ77C',
    carId: 'car-2',
    customerId: 'u-cust-2',
    ownerId: 'u-owner-2',
    startDate: addDays(todayISO(), 8),
    endDate: addDays(todayISO(), 14),
    days: 7,
    pickupLocation: 'Wuse 2, Abuja',
    renter: bookingRenter(customers[1]),
    subtotal: 580_000,
    serviceFee: 58_000,
    insuranceFee: 24_500,
    total: 662_500,
    status: 'pending',
    paymentStatus: 'unpaid',
    createdAt: addDays(todayISO(), -1),
  },
  {
    id: 'bk-3',
    reference: 'AG-1PD40M',
    carId: 'car-9',
    customerId: 'u-cust-1',
    ownerId: 'u-owner-1',
    startDate: addDays(todayISO(), -20),
    endDate: addDays(todayISO(), -16),
    days: 5,
    pickupLocation: 'Surulere, Lagos',
    renter: bookingRenter(customers[0]),
    subtotal: 425_000,
    serviceFee: 42_500,
    insuranceFee: 17_500,
    total: 485_000,
    status: 'completed',
    paymentStatus: 'paid',
    paymentReference: 'PSK_10ab77x',
    createdAt: addDays(todayISO(), -27),
  },
  {
    id: 'bk-4',
    reference: 'AG-6RT23V',
    carId: 'car-6',
    customerId: 'u-cust-3',
    ownerId: 'u-owner-1',
    startDate: addDays(todayISO(), -8),
    endDate: addDays(todayISO(), -5),
    days: 4,
    pickupLocation: 'Ikoyi, Lagos',
    renter: bookingRenter(customers[2]),
    subtotal: 480_000,
    serviceFee: 48_000,
    insuranceFee: 14_000,
    total: 542_000,
    status: 'cancelled',
    paymentStatus: 'refunded',
    paymentReference: 'PSK_55zq01p',
    createdAt: addDays(todayISO(), -15),
  },
  {
    id: 'bk-5',
    reference: 'AG-9LM55B',
    carId: 'car-4',
    customerId: 'u-cust-2',
    ownerId: 'u-owner-2',
    startDate: addDays(todayISO(), 1),
    endDate: addDays(todayISO(), 4),
    days: 4,
    pickupLocation: 'Victoria Island, Lagos',
    renter: bookingRenter(customers[1]),
    subtotal: 660_000,
    serviceFee: 66_000,
    insuranceFee: 14_000,
    total: 740_000,
    status: 'active',
    paymentStatus: 'paid',
    paymentReference: 'PSK_78hh22k',
    createdAt: addDays(todayISO(), -6),
  },
].map((b) => {
  const car = cars.find((c) => c.id === b.carId)!
  return {
    ...b,
    car: {
      id: car.id,
      name: car.name,
      brand: car.brand,
      model: car.model,
      images: car.images,
      pickupLocation: car.pickupLocation,
    },
  }
}) as Booking[]

export const reviews: Review[] = [
  {
    id: 'rv-1',
    carId: 'car-1',
    bookingId: 'bk-3',
    author: { id: 'u-cust-1', name: 'Ngozi Eze' },
    rating: 5,
    comment:
      'Spotless car and Chidi was waiting at the pickup point ten minutes early. Handover took five minutes. Would book again without hesitation.',
    photos: [],
    ownerReply: {
      comment: 'Thank you Ngozi! Always a pleasure â€” see you on the next trip.',
      createdAt: addDays(todayISO(), -14),
    },
    createdAt: addDays(todayISO(), -15),
  },
  {
    id: 'rv-2',
    carId: 'car-1',
    bookingId: 'bk-3',
    author: { id: 'u-cust-2', name: 'Samuel Ojo' },
    rating: 4,
    comment:
      'Great car, drove beautifully on the Lagosâ€“Ibadan expressway. Only note is that the fuel was slightly under full at pickup.',
    photos: [],
    createdAt: addDays(todayISO(), -32),
  },
  {
    id: 'rv-3',
    carId: 'car-2',
    bookingId: 'bk-2',
    author: { id: 'u-cust-3', name: 'Fatima Sani' },
    rating: 5,
    comment:
      'Took the Prado to Jos and back with five people and luggage. Comfortable the whole way, air conditioning ice cold.',
    photos: [],
    createdAt: addDays(todayISO(), -9),
  },
  {
    id: 'rv-4',
    carId: 'car-4',
    bookingId: 'bk-5',
    author: { id: 'u-cust-1', name: 'Ngozi Eze' },
    rating: 5,
    comment: 'Genuinely a special car. Amara is professional and the paperwork was seamless.',
    photos: [],
    createdAt: addDays(todayISO(), -4),
  },
]

export const transactions: Transaction[] = [
  {
    id: 'tx-1',
    bookingId: 'bk-1',
    reference: 'PSK_29fj20d',
    type: 'payment',
    amount: 212_000,
    channel: 'card',
    status: 'success',
    createdAt: addDays(todayISO(), -2),
  },
  {
    id: 'tx-2',
    bookingId: 'bk-3',
    reference: 'PSK_10ab77x',
    type: 'payment',
    amount: 485_000,
    channel: 'bank-transfer',
    status: 'success',
    createdAt: addDays(todayISO(), -27),
  },
  {
    id: 'tx-3',
    bookingId: 'bk-3',
    reference: 'PYT_10ab77x',
    type: 'payout',
    amount: 425_000,
    channel: 'bank-transfer',
    status: 'success',
    createdAt: addDays(todayISO(), -14),
  },
  {
    id: 'tx-4',
    bookingId: 'bk-4',
    reference: 'PSK_55zq01p',
    type: 'refund',
    amount: 542_000,
    channel: 'card',
    status: 'success',
    createdAt: addDays(todayISO(), -12),
  },
  {
    id: 'tx-5',
    bookingId: 'bk-5',
    reference: 'PSK_78hh22k',
    type: 'payment',
    amount: 740_000,
    channel: 'wallet',
    status: 'success',
    createdAt: addDays(todayISO(), -6),
  },
]

export const testimonials = [
  {
    id: 't-1',
    name: 'Ngozi Eze',
    role: 'Renter, Lagos',
    rating: 5,
    quote:
      'I booked a Camry for a four-day work trip and had the keys in my hand within an hour. The price I saw was the price I paid.',
  },
  {
    id: 't-2',
    name: 'Chidi Okonkwo',
    role: 'Car owner, Lagos',
    rating: 5,
    quote:
      'My two cars used to sit idle between contracts. On AUTOGO they earn about â‚¦600,000 a month and payouts land the day after each trip.',
  },
  {
    id: 't-3',
    name: 'Fatima Sani',
    role: 'Renter, Abuja',
    rating: 5,
    quote:
      'The GPS tracking gave my family real peace of mind on a long inter-state drive. Support answered on the first ring.',
  },
]
